name: Branch Protection

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            if [[ "${{ github.head_ref }}" != "staging" ]]; then
              echo "Only 'staging' can be merged into 'main'."
              exit 1
            fi
          elif [[ "${{ github.base_ref }}" == "staging" ]]; then
            if [[ "${{ github.head_ref }}" == "main" ]]; then
              echo "'main' cannot be merged into 'staging'."
              exit 1
            fi
          fi
